/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Returns application health, model version, training timestamp, and market data as-of date.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Options
         * @description Returns valid dropdown options: talukas, crops, soils, varieties.
         */
        get: operations["get_options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Card
         * @description Returns model metadata, evaluation results, and assumptions (JSON safe).
         */
        get: operations["get_model_card_api_model_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Report
         * @description Returns market price analysis and 6-month storage vs immediate selling plan.
         */
        get: operations["get_market_report_api_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advisory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Advisory
         * @description Generates tailored harvest, yield outlook, and market storage advisory for a soybean farmer.
         *     Returns JSON matching the model contract.
         */
        post: operations["create_advisory_api_advisory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/harvest-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Harvest Feedback
         * @description Records real-world farmer harvest observations to calibrate the harvest date model.
         *     Appends observation to data/harvest_feedback.csv.
         */
        post: operations["submit_harvest_feedback_api_harvest_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrain-harvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrain Harvest Model
         * @description Retrains the harvest date calibration using logged farmer feedback.
         *     Protected by the X-API-Key header.
         *     Requires at least 3 valid observations.
         *     Deep-copies the model before mutation, then atomically saves and hot-swaps.
         */
        post: operations["retrain_harvest_model_api_retrain_harvest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvisoryRequest */
        AdvisoryRequest: {
            /**
             * Name
             * @description Farmer's name
             * @default
             */
            name: string | null;
            /**
             * Taluka
             * @description Taluka in Sangli district
             */
            taluka: string;
            /**
             * Crop
             * @description Crop name (Soybean)
             * @default Soybean
             */
            crop: string;
            /**
             * Sowing Date
             * Format: date
             * @description Sowing date (YYYY-MM-DD)
             */
            sowing_date: string;
            /**
             * Soil
             * @description Soil type from options
             */
            soil: string;
            /**
             * Variety
             * @description Soybean variety (early, medium, late or full description)
             */
            variety: string;
            /**
             * Acres
             * @description Farm size in acres (must be > 0)
             */
            acres: number;
            /**
             * Storage Cost
             * @description Monthly storage cost in INR per quintal (>= 0)
             * @default 15
             */
            storage_cost: number;
            /**
             * Interest Rate
             * @description Monthly interest rate (between 0 and 0.1)
             * @default 0.01
             */
            interest_rate: number;
            /**
             * Today
             * @description Optional current date override for demo/testing
             */
            today?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarvestFeedbackRequest */
        HarvestFeedbackRequest: {
            /**
             * Sowing Date
             * Format: date
             * @description Sowing date (YYYY-MM-DD)
             */
            sowing_date: string;
            /**
             * Harvest Date
             * Format: date
             * @description Harvest date (YYYY-MM-DD)
             */
            harvest_date: string;
            /**
             * Variety
             * @description Variety: early, medium, or late
             */
            variety: string;
            /**
             * Taluka
             * @description Optional Sangli taluka
             */
            taluka?: string | null;
        };
        /** HarvestFeedbackResponse */
        HarvestFeedbackResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Feedback */
            feedback: {
                [key: string]: unknown;
            };
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Model Version */
            model_version: string;
            /** Trained At */
            trained_at: string;
            /** Market Data As Of */
            market_data_as_of: string;
        };
        /** RetrainResponse */
        RetrainResponse: {
            /** Status */
            status: string;
            /** Calibrated */
            calibrated: boolean;
            /** N Obs */
            n_obs: number;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_model_card_api_model_card_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_market_report_api_market_get: {
        parameters: {
            query?: {
                /** @description Monthly storage cost in INR per quintal */
                storage?: number;
                /** @description Monthly interest rate (e.g. 0.01 for 1%) */
                interest?: number;
                /** @description Optional Minimum Support Price in INR per quintal */
                msp?: number | null;
                /** @description Optional date override for analysis */
                today?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_advisory_api_advisory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvisoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_harvest_feedback_api_harvest_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HarvestFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarvestFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrain_harvest_model_api_retrain_harvest_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
